task_name: "reachqa"
dataset_path: hewei2001/ReachQA
answer_comparator_path: /mnt/petrelfs/share_data/sunhaoyu/weights/paraphrase-MiniLM-L6-v2
dataset_type: "unique" # Which means we need to implement load data logic sepretely for charxiv
generation_config:
  max_length: 2048
  # temperature: 0.6

