# base_dir: ../..
# log_folder: ../../logs/server_log
base_dir: AdaReasoner/tool_server/tool_workers
log_folder: AdaReasoner/tool_server/tool_workers/logs/server_log
partition: "ai_moe2"
default_calculate_gpus: 1
default_calculate_cpus: 12
default_control_cpus: 2
default_control_gpus: 0
default_heavy_calculate_gpus: 4
default_heavy_calculate_cpus: 32
retry_interval: 1
request_timeout: 10

controller_config:
  worker_name: controller
  job_name: controller
  calculate_type: control
  conda_env: "tool_server"
  srun_kwargs:
    w: "SH-IDC1-10-140-37-138"
  cmd:
    script-addr: ./online_workers/controller.py
    port: 21112
    host: "0.0.0.0"

tool_worker_config:
  - Point:
      worker_name: Point
      job_name: point
      calculate_type: control
      conda_env: "tool-server"
      srun_kwargs:
        w: "SH-IDC1-10-140-37-82"
      cuda_visible_devices: "4,5,6,7"
      cmd:
        script-addr: tool_server.tool_workers.online_workers.point_worker_parallel
        port: 50002
        host: "0.0.0.0"
        model_path: allenai/Molmo-7B-D-0924
  
  - Crop:
      worker_name: Crop
      job_name: crop
      calculate_type: control
      cmd:
        script-addr: tool_server.tool_workers.online_workers.crop_worker_prompt
        port: 20040
        host: "0.0.0.0"

  - OCR:
      worker_name: OCR
      job_name: ocr
      calculate_type: calculate
      node_list: "SH-IDC1-10-140-37-138"
      cuda_visible_devices: "6,7"
      use_apptainer: true
      # 使用原始干净镜像
      apptainer_image: "ubuntu20.04-py3.10-cuda11.8-cudnn8-transformer4.30.0_v1.0.0.sif"
      conda_env_path: "/miniconda3/envs/tool-server"
      cmd:
        script-addr: tool_server.tool_workers.online_workers.ocr_worker
        port: 20009
        host: "0.0.0.0"
        gpu_ids: "6,7"
        enable_multi_gpu: true
        max_concurrency: 4

  # - OCR:
  #     worker_name: OCR
  #     job_name: ocr
  #     calculate_type: calculate
  #     node_list: "SH-IDC1-10-140-37-41"
  #     cuda_visible_devices: "5"
  #     use_apptainer: true
  #     apptainer_image: "/mnt/petrelfs/sunhaoyu/visual-code/tool-server.sif"
  #     cmd:
  #       script-addr: tool_server.tool_workers.online_workers.ocr_worker_paddle_单卡
  #       port: 20009
  #       host: "0.0.0.0"

  # - DrawShape:
  #     worker_name: DrawShape
  #     job_name: draw_shape
  #     calculate_type: control
  #     cmd:
  #       script-addr: tool_server.tool_workers.online_workers.draw_shape_worker
  #       port: 20041
  #       host: "0.0.0.0"

  # - HighlightBox:
  #     worker_name: HighlightBox
  #     job_name: highlight_box
  #     calculate_type: control
  #     cmd:
  #       script-addr: tool_server.tool_workers.online_workers.highlight_box_worker
  #       port: 20042
  #       host: "0.0.0.0"

  # - MaskBox:
  #     worker_name: MaskBox
  #     job_name: mask_box
  #     calculate_type: control
  #     cmd:
  #       script-addr: tool_server.tool_workers.online_workers.mask_box_worker
  #       port: 20043
  #       host: "0.0.0.0"

  # - GetSubplotInfo:
  #     worker_name: GetSubplotInfo
  #     job_name: get_subplot_info
  #     calculate_type: control
  #     conda_env: "visual"
  #     cmd:
  #       script-addr: tool_server.tool_workers.online_workers.get_subplot_info_worker
  #       port: 20045
  #       host: "0.0.0.0"


  # - GetBarInfo:
  #     worker_name: GetBarInfo
  #     job_name: get_bar_info
  #     calculate_type: control
  #     conda_env: "visual"
  #     cmd:
  #       script-addr: tool_server.tool_workers.online_workers.get_bar_info_worker
  #       port: 20046
  #       host: "0.0.0.0"
