base_dir: /mnt/petrelfs/sunhaoyu/visual-code/Tool-Factory-Filter/tool_server/tool_workers
log_folder: /mnt/petrelfs/sunhaoyu/visual-code/Tool-Factory-Filter/tool_server/tool_workers/scripts/logs/parallel_point_test
partition: "ai_moe"
default_calculate_gpus: 1
default_calculate_cpus: 16
default_control_cpus: 2
default_control_gpus: 0
default_heavy_calculate_gpus: 4
default_heavy_calculate_cpus: 32
retry_interval: 1
request_timeout: 10
current_node: &node SH-IDC1-10-140-37-82

controller_config:
  worker_name: controller
  job_name: controller
  calculate_type: control
  conda_env: "tool_server"
  srun_kwargs:
    w: *node
  cmd:
    script-addr: ./online_workers/controller.py
    port: 50002
    host: "0.0.0.0"



tool_worker_config:
  - Point:
      worker_name: Point
      job_name: point
      calculate_type: control
      conda_env: "tool-server"
      srun_kwargs:
        w: *node
      cuda_visible_devices: "4,5,6,7"
      cmd:
        script-addr: tool_server.tool_workers.online_workers.point_worker_parallel
        port: 50002
        host: "0.0.0.0"
        model_path: allenai/Molmo-7B-D-0924