# base_dir: ../..
# log_folder: ../../logs/server_log
base_dir: /mnt/petrelfs/sunhaoyu/visual-code/Tool-Factory-Filter/tool_server/tool_workers
log_folder: /mnt/petrelfs/sunhaoyu/visual-code/Tool-Factory-Filter/tool_server/tool_workers/logs/server_log2
partition: "ai_moe"
default_calculate_gpus: 1
default_calculate_cpus: 12
default_control_cpus: 2
default_control_gpus: 0
retry_interval: 1
request_timeout: 10

controller_config:
  worker_name: controller
  job_name: controller
  calculate_type: control
  srun_kwargs:
    w: "SH-IDC1-10-140-37-82"  # 指定固定节点
  cmd:
    script-addr: ./online_workers/controller.py
    port: 30012
    host: "0.0.0.0"

tool_worker_config:
  - Point:
      worker_name: Point
      job_name: point
      calculate_type: control
      conda_env: "tool-server"
      srun_kwargs:
        w: "SH-IDC1-10-140-37-82"
      cuda_visible_devices: "0,1,2,3"
      cmd:
        script-addr: tool_server.tool_workers.online_workers.point_worker_parallel
        port: 40003
        host: "0.0.0.0"
        model_path: "/mnt/petrelfs/share_data/songmingyang/model/mm/tools/Molmo-7B-D-0924"

  - OCR:
      worker_name: OCR
      job_name: ocr
      calculate_type: calculate
      node_list: "SH-IDC1-10-140-37-82"
      cuda_visible_devices: "6,7"
      use_apptainer: true
      apptainer_image: "/mnt/petrelfs/share_data/sunhaoyu/sifs/tool-server.sif"
      cmd:
        script-addr: tool_server.tool_workers.online_workers.ocr_worker
        port: 20019
        host: "0.0.0.0"
        gpu_ids: "6,7"  # 指定使用的GPU ID
        enable_multi_gpu: true  # 启用多GPU推理
        max_concurrency: 5  # 增加并发数以支持多GPU
  - Crop:
      worker_name: Crop
      job_name: crop
      calculate_type: control
      cmd:
        script-addr: tool_server.tool_workers.online_workers.crop_worker_prompt
        port: 20055
        host: "0.0.0.0"