task_name: "chartgemma"
dataset_path: /mnt/petrelfs/sunhaoyu/visual-code/datasets/OpenThinkIMG-Chart-Test-994
# num_sample: 1000 # 最大1000
# num_sample: 50
dataset_type: "unique" # Which means we need to implement load data logic sepretely for charxiv
generation_config:
  max_length: 2048

