task_name: "web"
dataset_path: /visual-code/datasets/GUIChat/sft_v1
num_sample: 1500
dataset_type: "unique" # Which means we need to implement load data logic sepretely for charxiv
generation_config:
  max_length: 8192
  # temperature: 0.6

