task_name: "charxiv"
dataset_path: /mnt/petrelfs/sunhaoyu/visual-code/datasets/CharXiv
# num_sample: 500 # 一共2000
num_sample: 2000
dataset_type: "unique" # Which means we need to implement load data logic sepretely for charxiv
generation_config: # 一般只会设置max_length
  max_length: 2048

