model_args:
  model: openai
  model_args: pretrained=gpt-5-2025-08-07
  batch_size: 1
  max_rounds: 10
  model_mode: general
  

# 对于chartgemma数据集
task_args:
  # task_name: chartgemma,chartqa,charxiv,docvqa,ocrbench,reachqa,vstar
  task_name: vsp_test,vstar,hrbench,mme,pope,ocrbench
  tool_selection: Point,Draw2DPath,AStarWithPixelCoordinate,DetectBlackArea,InsertImage,OCR,Crop
  resume_from_ckpt:
    vsp: /mnt/petrelfs/songmingyang/code/reasoning/tool-agent/tool_server/tf_eval/scripts/logs/ckpt/unified/sec4_all_3tasks/gpt5_wtools/vsp.jsonl
    vsp_test: /mnt/petrelfs/songmingyang/code/reasoning/tool-agent/tool_server/tf_eval/scripts/logs/ckpt/unified/sec4_all_3tasks/gpt5_wtools/vsp_test.jsonl
    jigsaw_coco: /mnt/petrelfs/songmingyang/code/reasoning/tool-agent/tool_server/tf_eval/scripts/logs/ckpt/unified/sec4_all_3tasks/gpt5_wtools/jigsaw_coco.jsonl
    jigsaw_blink: /mnt/petrelfs/songmingyang/code/reasoning/tool-agent/tool_server/tf_eval/scripts/logs/ckpt/unified/sec4_all_3tasks/gpt5_wtools/jigsaw_blink.jsonl
    web_guichat: /mnt/petrelfs/songmingyang/code/reasoning/tool-agent/tool_server/tf_eval/scripts/logs/ckpt/unified/sec4_all_3tasks/gpt5_wtools/web_guichat.jsonl
    webmmu: /mnt/petrelfs/songmingyang/code/reasoning/tool-agent/tool_server/tf_eval/scripts/logs/ckpt/unified/sec4_all_3tasks/gpt5_wtools/webmmu.jsonl
    vstar: /mnt/petrelfs/songmingyang/code/reasoning/tool-agent/tool_server/tf_eval/scripts/logs/ckpt/unified/sec4_all_3tasks/gpt5_wtools/vstar.jsonl
    hrbench: /mnt/petrelfs/songmingyang/code/reasoning/tool-agent/tool_server/tf_eval/scripts/logs/ckpt/unified/sec4_all_3tasks/gpt5_wtools/hrbench.jsonl
    mme: /mnt/petrelfs/songmingyang/code/reasoning/tool-agent/tool_server/tf_eval/scripts/logs/ckpt/unified/sec4_all_3tasks/gpt5_wtools/mme.jsonl
    pope: /mnt/petrelfs/songmingyang/code/reasoning/tool-agent/tool_server/tf_eval/scripts/logs/ckpt/unified/sec4_all_3tasks/gpt5_wtools/pope.jsonl
    ocrbench: /mnt/petrelfs/songmingyang/code/reasoning/tool-agent/tool_server/tf_eval/scripts/logs/ckpt/unified/sec4_all_3tasks/gpt5_wtools/ocrbench.jsonl

  save_to_ckpt:
    vsp: /mnt/petrelfs/songmingyang/code/reasoning/tool-agent/tool_server/tf_eval/scripts/logs/ckpt/unified/sec4_all_3tasks/gpt5_wtools/vsp.jsonl
    vsp_test: /mnt/petrelfs/songmingyang/code/reasoning/tool-agent/tool_server/tf_eval/scripts/logs/ckpt/unified/sec4_all_3tasks/gpt5_wtools/vsp_test.jsonl
    jigsaw_coco: /mnt/petrelfs/songmingyang/code/reasoning/tool-agent/tool_server/tf_eval/scripts/logs/ckpt/unified/sec4_all_3tasks/gpt5_wtools/jigsaw_coco.jsonl
    jigsaw_blink: /mnt/petrelfs/songmingyang/code/reasoning/tool-agent/tool_server/tf_eval/scripts/logs/ckpt/unified/sec4_all_3tasks/gpt5_wtools/jigsaw_blink.jsonl
    web_guichat: /mnt/petrelfs/songmingyang/code/reasoning/tool-agent/tool_server/tf_eval/scripts/logs/ckpt/unified/sec4_all_3tasks/gpt5_wtools/web_guichat.jsonl
    webmmu: /mnt/petrelfs/songmingyang/code/reasoning/tool-agent/tool_server/tf_eval/scripts/logs/ckpt/unified/sec4_all_3tasks/gpt5_wtools/webmmu.jsonl
    vstar: /mnt/petrelfs/songmingyang/code/reasoning/tool-agent/tool_server/tf_eval/scripts/logs/ckpt/unified/sec4_all_3tasks/gpt5_wtools/vstar.jsonl
    hrbench: /mnt/petrelfs/songmingyang/code/reasoning/tool-agent/tool_server/tf_eval/scripts/logs/ckpt/unified/sec4_all_3tasks/gpt5_wtools/hrbench.jsonl
    mme: /mnt/petrelfs/songmingyang/code/reasoning/tool-agent/tool_server/tf_eval/scripts/logs/ckpt/unified/sec4_all_3tasks/gpt5_wtools/mme.jsonl
    pope: /mnt/petrelfs/songmingyang/code/reasoning/tool-agent/tool_server/tf_eval/scripts/logs/ckpt/unified/sec4_all_3tasks/gpt5_wtools/pope.jsonl
    ocrbench: /mnt/petrelfs/songmingyang/code/reasoning/tool-agent/tool_server/tf_eval/scripts/logs/ckpt/unified/sec4_all_3tasks/gpt5_wtools/ocrbench.jsonl

  middle_images_save_dir:
    vsp: /mnt/petrelfs/songmingyang/code/reasoning/tool-agent/tool_server/tf_eval/scripts/logs/ckpt/unified/sec4_all_3tasks/gpt5_wtools/middle_images
    jigsaw_blink: /mnt/petrelfs/songmingyang/code/reasoning/tool-agent/tool_server/tf_eval/scripts/logs/ckpt/unified/sec4_all_3tasks/gpt5_wtools/middle_images_jigsaw_blink

script_args:
  verbosity: INFO
  output_path: /mnt/petrelfs/songmingyang/code/reasoning/tool-agent/tool_server/tf_eval/scripts/logs/results/unified/sec4_all_3tasks/gpt5_wtools/qwen25_allres.jsonl
  if_use_tool: True
