task_name: "chartqa"
dataset_path: HuggingFaceM4/ChartQA
# image_dir_path: /mnt/petrelfs/share_data/suzhaochen/datasets/chartqa/image
# num_sample: 2500 # 最大2500
# num_sample: 50
dataset_type: "unique" # Which means we need to implement load data logic sepretely for charxiv
generation_config:
  max_length: 2048

