task_name: "webmmu"
dataset_path:  /mnt/petrelfs/share_data/sunhaoyu/datasets/web_evaluation/WebMMU
dataset_type: "unique" # Which means we need to implement load data logic sepretely for charxiv
generation_config:
  max_length: 8192
  # temperature: 0.6

