# config.yaml
task_name: "vsp"
dataset_path: "hitsmy/AdaEval-VSP" 
dataset_type: "hf" 
tasks:
  - "verify_test"  
  - "navigation_test"  
generation_config:
  max_length: 2048
  temperature: 0.7
num_sample: null 