# config.yaml
task_name: "vsp"
dataset_path: "/data/songmingyang/data/adareasoner/benchmarks/AdaEval-VSP-local"
dataset_type: "hf"
tasks:
  - "verify_test"
generation_config:
  max_length: 2048
  temperature: 0.7
num_sample: null
