task_name: "jigsaw_coco"
dataset_repo: "hitsmy/AdaEval-Jigsaw-COCO"  
dataset_type: "huggingface" 
use_auth_token: false
splits:
  - "test"
num_sample: null 
generation_config:
  max_length: 2048
  temperature: 0.2  

