model_args:
  model: vllm_models
  model_args: pretrained=/data/songmingyang/models/baselines/Qwen2.5-VL-7B-Instruct,tensor_parallel=1,limit_mm_per_prompt=10,gpu_memory_utilization=0.85,max_model_len=8192,enforce_eager=True,seed=1234
  batch_size: 64
  max_rounds: 1
  model_mode: general
task_args:
  task_name: vsp
  tool_selection: AStarWithPixelCoordinate,Draw2DPath,Point
  resume_from_ckpt:
    vsp: /data/songmingyang/code/reasoning/AdaReasoner-rebuttal/rebuttal_exps/qwen25vl_eval/no_tools/qwen25vl_7b/vsp/seed_1234/ckpt.jsonl
  save_to_ckpt:
    vsp: /data/songmingyang/code/reasoning/AdaReasoner-rebuttal/rebuttal_exps/qwen25vl_eval/no_tools/qwen25vl_7b/vsp/seed_1234/ckpt.jsonl
  middle_images_save_dir:
    vsp: /data/songmingyang/code/reasoning/AdaReasoner-rebuttal/rebuttal_exps/qwen25vl_eval/no_tools/qwen25vl_7b/vsp/seed_1234/middle_images
script_args:
  verbosity: INFO
  output_path: /data/songmingyang/code/reasoning/AdaReasoner-rebuttal/rebuttal_exps/qwen25vl_eval/no_tools/qwen25vl_7b/vsp/seed_1234/result.jsonl
  controller_addr: http://127.0.0.1:21112
  if_use_tool: false
  if_randomize_tool: false
